### ISSUE TITLE
Failing to generate layer fusion for model parameter (ResNet)

### ISSUE THREAD

**Issue by jstumpin** [01org/caffe#64] opened 2017-08-31 08:36 UTC
Below is the remaining excerpt of _model_fuse.py_ (after printing out the fused _prototxt_) for ResNet50:

> I0831 00:43:05.308976  8468 layer_factory.cpp:65] Creating layer input
> I0831 00:43:05.308976  8468 net.cpp:96] Creating Layer input
> I0831 00:43:05.308976  8468 net.cpp:413] input -> data
> I0831 00:43:05.309978  8468 net.cpp:134] Setting up input
> I0831 00:43:05.309978  8468 net.cpp:142] Top shape: 1 3 224 224 (150528)
> I0831 00:43:05.309978  8468 layer_factory.cpp:65] Creating layer conv1
> I0831 00:43:05.309978  8468 net.cpp:96] Creating Layer conv1
> I0831 00:43:05.309978  8468 net.cpp:444] conv1 <- data
> I0831 00:43:05.309978  8468 net.cpp:413] conv1 -> conv1
> I0831 00:43:05.309978  8468 net.cpp:134] Setting up conv1
> I0831 00:43:05.309978  8468 net.cpp:142] Top shape: 1 64 112 112 (802816)
> I0831 00:43:05.309978  8468 layer_factory.cpp:65] Creating layer pool1
> I0831 00:43:05.309978  8468 net.cpp:96] Creating Layer pool1
> I0831 00:43:05.309978  8468 net.cpp:444] pool1 <- conv1
> I0831 00:43:05.309978  8468 net.cpp:413] pool1 -> pool1
> I0831 00:43:05.310981  8468 net.cpp:134] Setting up pool1
> I0831 00:43:05.310981  8468 net.cpp:142] Top shape: 1 64 56 56 (200704)
> I0831 00:43:05.310981  8468 layer_factory.cpp:65] Creating layer pool1_pool1_0_split
> I0831 00:43:05.310981  8468 net.cpp:96] Creating Layer pool1_pool1_0_split
> I0831 00:43:05.310981  8468 net.cpp:444] pool1_pool1_0_split <- pool1
> I0831 00:43:05.310981  8468 net.cpp:413] pool1_pool1_0_split -> pool1_pool1_0_split_0
> I0831 00:43:05.310981  8468 net.cpp:413] pool1_pool1_0_split -> pool1_pool1_0_split_1
> I0831 00:43:05.310981  8468 net.cpp:134] Setting up pool1_pool1_0_split
> I0831 00:43:05.310981  8468 net.cpp:142] Top shape: 1 64 56 56 (200704)
> I0831 00:43:05.310981  8468 net.cpp:142] Top shape: 1 64 56 56 (200704)
> I0831 00:43:05.310981  8468 layer_factory.cpp:65] Creating layer res2a_branch1
> I0831 00:43:05.310981  8468 net.cpp:96] Creating Layer res2a_branch1
> I0831 00:43:05.310981  8468 net.cpp:444] res2a_branch1 <- pool1_pool1_0_split_0
> I0831 00:43:05.310981  8468 net.cpp:413] res2a_branch1 -> res2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:134] Setting up res2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:142] Top shape: 1 256 56 56 (802816)
> I0831 00:43:05.311985  8468 layer_factory.cpp:65] Creating layer bn2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:96] Creating Layer bn2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:444] bn2a_branch1 <- res2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:400] bn2a_branch1 -> res2a_branch1 (in-place)
> I0831 00:43:05.311985  8468 net.cpp:134] Setting up bn2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:142] Top shape: 1 256 56 56 (802816)
> I0831 00:43:05.311985  8468 layer_factory.cpp:65] Creating layer scale2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:96] Creating Layer scale2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:444] scale2a_branch1 <- res2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:400] scale2a_branch1 -> res2a_branch1 (in-place)
> I0831 00:43:05.311985  8468 layer_factory.cpp:65] Creating layer scale2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:134] Setting up scale2a_branch1
> I0831 00:43:05.311985  8468 net.cpp:142] Top shape: 1 256 56 56 (802816)
> I0831 00:43:05.311985  8468 layer_factory.cpp:65] Creating layer res2a_branch2a
> I0831 00:43:05.311985  8468 net.cpp:96] Creating Layer res2a_branch2a
> I0831 00:43:05.311985  8468 net.cpp:444] res2a_branch2a <- pool1_pool1_0_split_1
> I0831 00:43:05.311985  8468 net.cpp:413] res2a_branch2a -> res2a_branch2a
> I0831 00:43:05.312988  8468 net.cpp:134] Setting up res2a_branch2a
> I0831 00:43:05.312988  8468 net.cpp:142] Top shape: 1 64 56 56 (200704)
> I0831 00:43:05.312988  8468 layer_factory.cpp:65] Creating layer res2a_branch2b
> I0831 00:43:05.312988  8468 net.cpp:96] Creating Layer res2a_branch2b
> I0831 00:43:05.312988  8468 net.cpp:444] res2a_branch2b <- res2a_branch2a
> I0831 00:43:05.312988  8468 net.cpp:413] res2a_branch2b -> res2a_branch2b
> I0831 00:43:05.313990  8468 net.cpp:134] Setting up res2a_branch2b
> I0831 00:43:05.316141  8468 net.cpp:142] Top shape: 1 64 56 56 (200704)
> I0831 00:43:05.316141  8468 layer_factory.cpp:65] Creating layer res2a_branch2c
> I0831 00:43:05.316141  8468 net.cpp:96] Creating Layer res2a_branch2c
> I0831 00:43:05.317145  8468 net.cpp:444] res2a_branch2c <- res2a_branch2b
> I0831 00:43:05.317145  8468 net.cpp:444] res2a_branch2c <- res2a_branch1
> I0831 00:43:05.317145  8468 net.cpp:413] res2a_branch2c -> res2a
> F0831 00:43:05.317145  8468 layer.hpp:430] Check failed: bottom.size() == top.size() (2 vs. 1) Convolution Layer produces one top blob as output for each bottom blob input.
> *** Check failure stack trace: ***

**Comment by gongzg** [comment] 2017-08-31 10:06
The fused convolution layer may have 2 bottoms and 1 top. I already modify the corresponding condition check to allow this case:
You can check the following code:

  virtual inline bool EqualNumBottomTopBlobs() const {
    return IsFusedWithEltwiseReLU() ? false : true;
  }
in the following file:
include/caffe/layers/conv_spatial_layer.hpp

Only the 01org's inference-optimize branch could support layer fusion, If using the BVLC OpenCL branch to handle the fused prototxt, you will hit this issue.

**Comment by jstumpin** [comment] 2017-08-31 23:27
I do have such condition check in that header and I do test against this particular branch, yet the issue prevails.

**Comment by gongzg** [comment] 2017-09-01 01:00
@jstumpin did you try a clean build? caffe's build system has a known dependency issue. Sometimes, the header file changed but the corresponding objects will not be rebuilt. If you already did a clean build then ignore this advice. If that is the case, you may have to debug it further by using gdb to break at the layer.hpp's 430 line and see whath happen there.

**Comment by jstumpin** [comment] 2017-09-02 07:41
For a workaround, I've made the following changes:

1. CHECK_EQ(bottom.size(), top.size()) to CHECK_GE(bottom.size(), top.size()) in layer.hpp (line: 430)
2. CHECK(bottom[0]->shape() == bottom[bottom_id]->shape()) in base_conv_layer.cpp (line: 209)

Results (ResNet50):

- Original - 20 images/sec
- Fused - 75 images/sec

**Comment by jstumpin** [comment] 2017-09-03 09:25
Given above runtimes, as far as inferencing is concerned, I wonder how much more could FP16 contribute (especially with regards to ResNets)? Is there any pre-built caffemodel that I can readily test? My understanding is that the only way for to support FP16 is to train in FP16 (offline adaptation tools like NVIDIA's TensorRT or Intel's Model Optimizer is not envisioned in the roadmap I reckon). 

On a side note, in the spirit of practical deployment, despite not having specified VIENNACL_CACHE_PATH, why do I have "spatialkernels" folder in the root path? Does this mean caching is enabled? If so, is there any other ways to expedite the execution further because it seems rather slow even for consecutive runs (first run is definitely much longer)?

**Comment by gongzg** [comment] 2017-09-06 02:58
@jstumpin Thanks for update the performance number,but the performance number are too good to be true. Could you double check the which device you are actually using? My best guess is that you may be using the dGPU device rather than the iGPU. That guess can also explain why you met the assertion.

**Comment by gongzg** [comment] 2017-09-06 03:27
As to performance gain with FP16 over FP32, it depends. In general, if the net model has too many tiny layers which each layer only takes 1ms or much less than 1ms, it will be only about 15% performance gain or even less, for example the googlenet or resnet101. Otherwise, it could get noticable performance gain, say about 50% to 70% performance gain, for example the alexnet or vgg.

**Comment by jstumpin** [comment] 2017-09-06 04:37
As I said, that was just a forward pass (i.e. net_->Forward()) measurement (1/0.0009784 = 1,022 imgs/sec on average for AlexNet). If one considers the whole prediction process (minus reading the image), AlexNet would score a modest 35 imgs/sec. I'd be getting double that amount if I were to use a dGPU (NVIDIA Quadro K4200). For ResNet50, I'm getting somewhat similar performance like what you've published [here](https://github.com/01org/caffe/issues/63#issuecomment-325892654).

Apparently FP16 is only fruitful when it reaches a certain number of [batches](https://software.intel.com/en-us/forums/computer-vision/topic/735748). If that is the case, and you seems to imply similar notion, tiny layered nets such as ResNets won't reap much gain over this strategy. Moreover, batching for these kinda nets won't see as dramatic gain as simpler nets such as AlexNet would.

Ultimately, seeing both as opensource solutions, how much of an overlap does this branch and [this one]
 (https://software.intel.com/en-us/articles/accelerating-deep-learning-inference-with-intel-processor-graphics)? Could it be possible to feed this branch's fused layer topology into ModelOptimizer's input (thus gaining the FP32->FP16 conversion without retraining)?

**Comment by gongzg** [comment] 2017-09-06 05:56
Forward only is also too fast. Not sure how do you measure the time, I suppose you are using the following method, if I were wrong, please correct me.

gettimeofday(&t0, NULL);
for(i = 0; i < iter; i++)
net_->forward()
gettimeofday(&t1, NULL);

If it is the case, then the measurement may not be accurate, because the output data of the net_ has never been accessed, thus all the OCL command queue never get a chance to be pushed into KMD's ring buffer. Only when the buffer length is larger than a threshold, the UMD driver will push the ring command queue to KMD to execute. To avoid this type of issue, you may consider the following way:
gettimeofday(&t0, NULL);
for(i = 0; i < iter; i++) {
  net_->forward();
  Caffe::Synchronize(Caffe::GetDefaultDevice()->id());
}
gettimeofday(&t1, NULL);

**Comment by gongzg** [comment] 2017-09-06 06:11
clCaffe and clDNN share some kernels at the beginning and diverged as different design purpose. clDNN's purpose is to support some specific use case one by one, and clCaffe's purpose is to support generic net models. That's the reason why you saw the clDNN has some weird performance issue (FP16 with batch8 is much worse than FP32 with batch8 but with batch1 FP16 is much better). Those issues are just because clDNN hasn't worked on optimizing them. with clDNN's new releases, those issues will get fixed I believe. 

For clCaffe, there are much less issues of that type. And clCaffe's layer fusion is not compatible with clDNN's model optimizer.

**Comment by gongzg** [comment] 2017-09-06 06:19
The performance gain for FP16 over FP32 doesn't highly depend on the batch size. For example, for batch 1 VGG16 or Yolo2, FP16 could get about 1.6x speed of FP32.

**Comment by gongzg** [comment] 2017-09-06 06:27
The batch size matters for those tiny-layer net models, such as resnet. Take an example, for Resnet50, with batch size 1, FP16 could only get 15% performance gain over FP32. But with batch size 16, FP16 could get 53% performance gain over FP32.

**Comment by jstumpin** [comment] 2017-09-08 03:43
Didn't notice about the Caffe::Synchronize method, it is not implemented in other branches of Caffe that I was working on. Should I do the same for these branches if a fair comparison is warranted? Anyhow, I've updated the flawed reported [results](https://github.com/01org/caffe/issues/64#issuecomment-326728648).

Can I train a model using this branch without Intel Spatial support (since the machine is equipped a dGPU) and with FP16 precision, subsequently deploy the model on an iGPU machine, fused the layers using this branch but this time with Intel Spatial support, and ultimately do the inference? If it is doable, do you foresee any performance penalty in the proposed pipeline?

**Comment by gongzg** [comment] 2017-09-08 05:18
It's doable and actually that's tye typical work flow. There will be no peformance penalty. And you may not have to train the net model by using Fp16. You can use FP32 training result directly. Please be noted, you need to normalize the input data to [-1, 1] or [0, 1] just like Yolo2 or the MobilenetSSD. Then the weights could be used by fp16 version caffe directly with almost no accuracy lost compare to FP32. Actually, current clCaffe only support FP32 or double weights even for the FP16 version of clCaffe.

**Comment by jstumpin** [comment] 2017-09-08 23:04
Sounds dandy but I'm facing issue building caffe-fp16.bin. I shall open up a new thread.

**Comment by gongzg** [comment] 2017-09-13 09:21
I'm going to close this issue as it seems not an issue anymore.

**Closed by gongzg** 2017-09-13 09:21 UTC

**Comment by kodonnell** [comment] 2018-05-19 10:59
I'm seeing this issue. I can confirm that I also have the [correct header](https://github.com/01org/caffe/issues/64#issuecomment-326251217). 

Actually ... now it all works. I didn't rebuild anything ... just ran the tuning a bit and interrupted etc. Anyway - I did see it first time, but not now. I'll provide more detail if I see it again.
