### ISSUE TITLE
Intel HD Graphics 6000 backward incompatibility

### ISSUE THREAD

**Issue by jstumpin** [01org/caffe#98] opened 2017-12-12 05:57 UTC
### Issue summary
Successfully built and ran Caffe on Intel Iris Plus Graphics 650 but unable to reproduce tangible result when deployed on an older NUC (NUC5i5RYH) with an older iGPU (Intel HD Graphics 6000).

### Steps to reproduce
Running classification.cpp (specifically, net->Forward()) would trigger an erroneous output such as [this](https://gist.github.com/jstumpin/598dd3fea9d99d1a4fc8edb8790dcf35).

### Your system configuration
Intel Spatial is enabled. Here are the outputs for Caffe's [device query](https://gist.github.com/jstumpin/f3878499450712e4c9120c6e456205d7) and [clinfo](https://gist.github.com/jstumpin/a8ffb4cfbdec306f6efbb7f3e9542f05) respectively.

**Comment by gongzg** [comment] 2017-12-12 08:27
@jstumpin I just tried clCaffe on BDW and here is my clinfo:
Number of devices                                 2
  Device Name                                     Intel(R) HD Graphics
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0
  Driver Version                                  r5.0.63503
  Device OpenCL C Version                         OpenCL C 2.0
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               23
  Max clock frequency                             600MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     by <unknown> (0x7FC100000000)
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              32
  Preferred / native vector sizes

The FP32 version should work fine with the above driver version. The FP16 version will not work properly on BDW platform due to a known driver issue.

**Comment by jstumpin** [comment] 2017-12-12 15:07
The output is indeed from FP32 version of classification.cpp. Running "caffe.exe time -model NonFusedNetwork.prototxt -gpu 0 -phase TEST -iterations 20" ended with the same outcome.

**Comment by gongzg** [comment] 2017-12-13 00:20
It seems that your driver version"  Driver version:				 20.19.15.4624" is out-of-date. I can't reproduce this issue with the latest "Driver Version r5.0.63503". You can try the latest driver at the following link:
http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip

**Comment by jstumpin** [comment] 2017-12-13 04:16
It so happens I'm using Windows. Upgraded to ver. 20.19.15.4835 from https://downloadcenter.intel.com/download/27267/Graphics-Intel-Graphics-Driver-for-Windows-15-40-?product=86211 ,no dice still.

**Comment by gongzg** [comment] 2017-12-13 04:59
I don't have a Windows BDW device in hand. Could you share a full error log including all the error message?

**Comment by jstumpin** [comment] 2017-12-14 02:20
Here's the [caffe.log](https://gist.github.com/jstumpin/60cbc9ace0e146e3c833e4a4eedd6794) where it terminated prematurely, and here's the complete [std output](https://gist.github.com/jstumpin/1f596288064d8cb4bd19ea5bd80c8e2d).

**Comment by gongzg** [comment] 2017-12-14 02:26
I can't find any compilation error message. Could you also capture those message as well including both the stdout and stderr?

**Comment by jstumpin** [comment] 2017-12-14 02:33
This is deployment-only release testing, hence no build/compilation messages. How do I ensure the build will run on multiple targeted machines (but still having similar iGPUs)? Do I have to limit the options (e.g. without Isaac etc.)?

**Comment by gongzg** [comment] 2017-12-14 02:34
@jstumpin compilation error message means the runtime opencl computation error message, not the clcaffe's compilation error meessage. BTW one thing may worth to have a try is to find driver 4815 or 4729

**Comment by jstumpin** [comment] 2017-12-14 03:09
Based on these available [drivers](https://downloadcenter.intel.com/product/97501/Graphics-for-5th-Generation-Intel-Processors), I downgraded to 4703 without improvement. There is no runtime error, only actual code fragments posed as 'error message' if one could call it that.

**Comment by gongzg** [comment] 2017-12-14 03:31
Oh, i didnot notice the build error code is -43 which means this is a build option error not a real compilation error, I will check again.

**Comment by gongzg** [comment] 2017-12-14 05:34
@jstumpin could you try the following patch?

diff --git a/src/caffe/greentea/cl_kernels.cpp b/src/caffe/greentea/cl_kernels.cpp
index bb45158..04ee1bd 100644
--- a/src/caffe/greentea/cl_kernels.cpp
+++ b/src/caffe/greentea/cl_kernels.cpp
@@ -9085,8 +9085,8 @@ viennacl::ocl::program & RegisterKernels(viennacl::ocl::context *ctx) {
   }
   bool is_beignet = ctx->devices()[0].opencl_c_version().find("beignet")
                     != std::string::npos;
-  if (!is_beignet)
-    options += (" -cl-no-subgroup-ifp ");
+  //if (!is_beignet)
+  //  options += (" -cl-no-subgroup-ifp ");
   ctx->build_options(options);
   viennacl::ocl::program &program = ctx->add_program(kernel_program,
       "kernel_program");
@@ -9159,8 +9159,8 @@ viennacl::ocl::context *ctx, string name, string options) {
   }
   bool is_beignet = ctx->devices()[0].opencl_c_version().find("beignet")
                     != std::string::npos;
-  if (!is_beignet)
-    options += (" -cl-no-subgroup-ifp ");
+  //if (!is_beignet)
+  //  options += (" -cl-no-subgroup-ifp ");
   if(ctx->devices()[0].extensions().find("cl_intel_subgroups")!= std::string::npos) {
     options += " -DHAS_INTEL_SUBGROUPS ";
   }

**Comment by jstumpin** [comment] 2017-12-14 06:55
The patch does fixed the error but now the prediction accuracy as well as the run time are way off. The good thing is, the patch doesn't seem to affect performance of the source machine (the one with Iris 650).

**Comment by gongzg** [comment] 2017-12-14 07:22
We didn't pretune the convolution kernels for BDW platforms, so you can set the following environment variable before you run your application:
set CLCAFFE_IGNORE_PRETUNE=1
Then it will trigger auto-tuning, wait it to finish to see whether it will get better result.

BTW, you may need to upgrade the driver version to the latest one.

BTW, The patch does affect my platform's performance, get about 8% down. I will work out a better fix latter.

**Comment by jstumpin** [comment] 2017-12-14 09:21
I got "Verification was not successful, fallback to basic kernel" if batchsize > 1 and it stalled indefinitely. Other than that, it works! Iris 650 runs at 0.018s on average, where as HD 6000 scored 0.047s.

**Comment by gongzg** [comment] 2017-12-14 09:30
The fallback indicates compiler bug which force it fallback to very slow basic kernel and that the reason why you get much longer inference time on HD6000. I don't have too much things to do with the compiler issue on BDW platform, and if you don't have new issue, I'm going to close this one.

**Comment by jstumpin** [comment] 2017-12-14 09:53
Accuracy seems to tally. Only the runtime is lagged. If there's no workaround for the batch, I guess you can close it. Thanks.

**Closed** 2017-12-14 09:55 UTC
